# Generated by Django 4.2.1 on 2023-06-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=200, verbose_name='标题')),
                ('conten', models.TextField(verbose_name='内容')),
                ('c_tim', models.DateField(verbose_name='创建日期')),
            ],
        ),
    ]
